name: Main workflow

on:
  - push
  - workflow_dispatch


jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        ocaml-compiler:
          - 4.08.x
          - 4
          - 5
        include:
          - ocaml-compiler: 4.08.x
            packages: 'ppx_protocol_conv.opam ppx_protocol_conv_json.opam ppx_protocol_conv_msgpack.opam ppx_protocol_conv_xmlm.opam ppx_protocol_conv_yaml.opam ppx_protocol_conv_xml_light.opam'
          - ocaml-compiler: 4
            packages: 'ppx_protocol_conv.opam ppx_protocol_conv_json.opam ppx_protocol_conv_msgpack.opam ppx_protocol_conv_xmlm.opam ppx_protocol_conv_yaml.opam ppx_protocol_conv_xml_light.opam'
          - ocaml-compiler: 5
            packages: 'ppx_protocol_conv.opam ppx_protocol_conv_json.opam ppx_protocol_conv_msgpack.opam ppx_protocol_conv_xmlm.opam ppx_protocol_conv_yaml.opam ppx_protocol_conv_xml_light.opam'
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use OCaml ${{ matrix.ocaml-compiler }}
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}
          opam-local-packages: ${{ matrix.packages }}

      - run: |
          opam install . --deps-only --with-doc --with-test
          opam exec -- dune runtest

      - run: |
          for package in ${{ matrix.packages }}; do
            opam install ${package/.opam/} --with-doc --with-test
          done
